// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhaKeIl6sswFTl2_hLedZ47_tpLXGU-Hc',
    appId: '1:654699958000:web:fa66cc998b0622a868fc35',
    messagingSenderId: '654699958000',
    projectId: 'ucbs-attendance-system-4cec1',
    authDomain: 'ucbs-attendance-system-4cec1.firebaseapp.com',
    storageBucket: 'ucbs-attendance-system-4cec1.firebasestorage.app',
    measurementId: 'G-S1QZYQW029',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8gCAnUJYZmaYFRCJ8-bqzlLEonGvdsiY',
    appId: '1:654699958000:android:3aeeec15c846e88568fc35',
    messagingSenderId: '654699958000',
    projectId: 'ucbs-attendance-system-4cec1',
    storageBucket: 'ucbs-attendance-system-4cec1.firebasestorage.app',
  );
}
